# Generated by Django 6.0.6 on 2026-06-30 12:19

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('track_type', models.CharField(choices=[('civil_services', 'Civil Services / UPSC'), ('technical', 'Technical Interview'), ('behavioral', 'Behavioral Interview'), ('custom', 'Custom')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict, help_text='Strengths/weak-areas summary generated at session end.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='interviews.track')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferenceSnippet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('source', models.CharField(blank=True, max_length=255)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='interviews.track')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('topic', models.CharField(blank=True, max_length=120)),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=2)),
                ('reference_answer', models.TextField(blank=True, help_text='Optional model answer or key points, used by the evaluation agent.')),
                ('rubric', models.JSONField(blank=True, default=dict, help_text="Per-question scoring criteria, e.g. {'structure': 0.3, 'depth': 0.4, 'relevance': 0.3}")),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.track')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField(help_text='Snapshot of the question actually asked (covers agent-generated questions too).')),
                ('order', models.PositiveIntegerField(default=0)),
                ('answer_text', models.TextField(blank=True)),
                ('evaluation', models.JSONField(blank=True, default=dict, help_text="Structured rubric scores + rationale from the evaluation agent, e.g. {'scores': {'structure': 7, 'depth': 6}, 'rationale': '...'}")),
                ('follow_up_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='interviews.turn')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turns', to='interviews.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='interviews.session')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
