# Generated by Django 6.0.6 on 2026-06-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['name']},
        ),
    ]
